// <auto-generated />
using System;
using Core_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core_Project.Migrations
{
    [DbContext(typeof(CoreContext))]
    partial class CoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core_Project.DataBase.CF", b =>
                {
                    b.Property<string>("STUDENT_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BATCH_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENT_ID");

                    b.ToTable("CF");
                });

            modelBuilder.Entity("Core_Project.DataBase.CORE_STUDENTS", b =>
                {
                    b.Property<string>("SL_NO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CORE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("IDB_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICTURE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STUDENT_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SUB_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SL_NO");

                    b.HasIndex("STUDENT_ID");

                    b.HasIndex("SUB_ID");

                    b.ToTable("CORE_STUDENTS");
                });

            modelBuilder.Entity("Core_Project.DataBase.IDB_COURS", b =>
                {
                    b.Property<string>("SUB_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDB_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SUB_ID");

                    b.ToTable("IDB_COURS");
                });

            modelBuilder.Entity("Core_Project.DataBase.CORE_STUDENTS", b =>
                {
                    b.HasOne("Core_Project.DataBase.CF", "CF")
                        .WithMany("CORE_STUDENTS")
                        .HasForeignKey("STUDENT_ID");

                    b.HasOne("Core_Project.DataBase.IDB_COURS", "corestudents")
                        .WithMany("corestudents")
                        .HasForeignKey("SUB_ID");

                    b.Navigation("CF");

                    b.Navigation("corestudents");
                });

            modelBuilder.Entity("Core_Project.DataBase.CF", b =>
                {
                    b.Navigation("CORE_STUDENTS");
                });

            modelBuilder.Entity("Core_Project.DataBase.IDB_COURS", b =>
                {
                    b.Navigation("corestudents");
                });
#pragma warning restore 612, 618
        }
    }
}
